
spring:
  datasource:
    url: "jdbc:IRIS://172.17.0.2:1972/USER"
    driver-class-name: "com.intersystems.jdbc.IRISDriver"
    hikari:
      username: "_SYSTEM"
      password: "SYS"
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000

  jpa:
    database-platform: "org.hibernate.dialect.InterSystemsIRISDialect"
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    br.com.hive: TRACE
